FROM amd64/gcc:13.2 as builder

SHELL [ "/bin/bash", "-c" ]

WORKDIR /app

COPY Makefile .

COPY app/ app/

RUN ["make"]

RUN ["find", ".", "-type", "f", "!", "-name", "compiled-app", "-exec", "rm", "-f", "{}", "+"]
RUN ["rm", "-rf", "app/"]

ENTRYPOINT [ "./compiled-app" ]